#!/usr/bin/env bash
# setup-podman.sh — one-time / idempotent setup for the exam-ready production
# deploy on this server (practice.tecbizsolutions.com). Run as the openclaw
# user (rootless podman), NOT root.
#
# What this does (in order):
#   1. Verifies prerequisites (podman present, repo on main, app/Dockerfile exists)
#   2. Generates ~/srv/exam-readiness/exam-ready.env with DATABASE_URL + SESSION_SECRET
#      AND a freshly generated POSTGRES_PASSWORD (shared by db + app containers).
#   3. Copies quadlet units to ~/.config/containers/systemd/
#   4. systemctl --user daemon-reload
#   5. Inserts the @practice host block into /home/openclaw/srv/caddy/Caddyfile
#      (idempotent: skips if marker present); caddy validate before restart
#   6. systemctl --user restart caddy
#   7. systemctl --user start exam-ready-db   (waits for pg_isready)
#   8. Builds the app image from app/Dockerfile
#   9. systemctl --user start exam-ready-app   (waits for 200/307 on /login)
#  10. Runs prisma migrate deploy in the running app container
#  11. First-run-only: runs prisma db seed (gated by EXAMREADY_SEEDED=1)
set -euo pipefail

REPO_DIR="${REPO_DIR:-/home/openclaw/srv/exam-readiness}"
DOMAIN="practice.tecbizsolutions.com"
APP_PORT=3010
DB_NAME="examready"
DB_USER="examready"
ENV_FILE="$REPO_DIR/exam-ready.env"
QUADLETS_DIR="$HOME/.config/containers/systemd"
CADDYFILE="/home/openclaw/srv/caddy/Caddyfile"

bold() { printf '\033[1m%s\033[0m\n' "$*"; }
ok()   { printf '  \033[32m✓\033[0m %s\n' "$*"; }
warn() { printf '  \033[33m!\033[0m %s\n' "$*"; }
err()  { printf '  \033[31m✗\033[0m %s\n' "$*" >&2; }

# ── 1. Prereqs ──────────────────────────────────────────────────────────────
bold "==> 1/11  Verifying prerequisites"
command -v podman >/dev/null 2>&1 || { err "podman not found on PATH"; exit 1; }
ok "podman $(podman --version | awk '{print $3}')"
[ -d "$REPO_DIR" ] || { err "prod clone missing: $REPO_DIR (git clone --branch main --single-branch https://github.com/bistec-oss/exam-readiness-program.git $REPO_DIR)"; exit 1; }
[ -f "$REPO_DIR/app/Dockerfile" ] || { err "$REPO_DIR/app/Dockerfile missing"; exit 1; }
CURRENT_BRANCH=$(git -C "$REPO_DIR" rev-parse --abbrev-ref HEAD)
ok "repo on branch $CURRENT_BRANCH at $REPO_DIR"
[ -f "$CADDYFILE" ] || { err "central Caddyfile missing at $CADDYFILE"; exit 1; }
ok "central Caddyfile present"

# ── 2. Environment file ─────────────────────────────────────────────────────
bold "==> 2/11  Generating $ENV_FILE"
mkdir -p "$REPO_DIR"
if [ ! -f "$ENV_FILE" ]; then
  DB_PASS=$(openssl rand -base64 24 | tr -d '/+=' | cut -c1-24)
  SESSION_SECRET=$(openssl rand -base64 32)
  {
    printf 'NODE_ENV=production\n'
    printf 'PORT=%s\n' "$APP_PORT"
    printf 'DATABASE_URL=postgresql://%s:%s@db:5432/%s\n' "$DB_USER" "$DB_PASS" "$DB_NAME"
    printf 'SESSION_SECRET=%s\n' "$SESSION_SECRET"
    printf 'POSTGRES_PASSWORD=%s\n' "$DB_PASS"
  } > "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  ok "wrote env file (mode 0600) with generated DB password + session secret"
else
  warn "env file already exists, leaving alone"
fi

# ── 3. Copy quadlet units ───────────────────────────────────────────────────
bold "==> 3/11  Installing podman quadlets"
mkdir -p "$QUADLETS_DIR"
cp "$REPO_DIR/podman/exam-ready-db.container"  "$QUADLETS_DIR/"
cp "$REPO_DIR/podman/exam-ready-app.container" "$QUADLETS_DIR/"
cp "$REPO_DIR/podman/exam-ready-db.volume"     "$QUADLETS_DIR/"
cp "$REPO_DIR/podman/exam-ready.network"       "$QUADLETS_DIR/"
ok "copied 4 quadlet units to $QUADLETS_DIR"

# ── 4. systemd reload ───────────────────────────────────────────────────────
bold "==> 4/11  Reloading systemd --user"
systemctl --user daemon-reload
ok "reloaded"

# ── 5. Caddy @practice host block ───────────────────────────────────────────
bold "==> 5/11  Inserting @practice block into $CADDYFILE"
MARKER="### exam-ready — auto-generated by setup-podman.sh — do not edit"
if grep -qF "$MARKER" "$CADDYFILE"; then
  warn "marker found, skipping (idempotent)"
else
  python3 - "$CADDYFILE" "$MARKER" <<'PY'
import sys, pathlib
path, marker = sys.argv[1], sys.argv[2]
src = pathlib.Path(path).read_text()
block = f"""
{marker}
@practice host practice.tecbizsolutions.com
handle @practice {{
    reverse_proxy 127.0.0.1:3010
}}
"""
needle = "http://:8080 {"
i = src.find(needle)
if i < 0:
    raise SystemExit("could not find 'http://:8080 {' in central Caddyfile")
new = src[:i] + block.lstrip("\n") + "\n" + src[i:]
pathlib.Path(path).write_text(new)
print("inserted @practice block")
PY
  ok "@practice host block inserted"
fi

if command -v caddy >/dev/null 2>&1; then
  bold "==> 5b/11  Validating Caddyfile"
  if caddy validate --config "$CADDYFILE" --adapter '' >/dev/null 2>&1; then
    ok "caddy validate passed"
  else
    err "caddy validate FAILED — fix the Caddyfile before re-running setup"
    caddy validate --config "$CADDYFILE" --adapter '' 2>&1 || true
    exit 1
  fi
fi

# ── 6. Restart caddy ────────────────────────────────────────────────────────
bold "==> 6/11  Restarting caddy (admin API is off, so a reload is not possible)"
systemctl --user restart caddy
sleep 2
ok "caddy restarted"

# ── 7. Start db container ───────────────────────────────────────────────────
bold "==> 7/11  Starting exam-ready-db"
systemctl --user start exam-ready-db.service
for i in $(seq 1 30); do
  if podman exec exam-ready-db pg_isready -U "$DB_USER" -d "$DB_NAME" >/dev/null 2>&1; then
    ok "postgres is ready (took ${i}s)"
    break
  fi
  sleep 1
  if [ "$i" = "30" ]; then
    err "postgres did not become ready in 30s"
    podman logs exam-ready-db 2>&1 | tail -30 || true
    exit 1
  fi
done

# ── 8. Build app image ──────────────────────────────────────────────────────
bold "==> 8/11  Building exam-ready-app image from app/Dockerfile"
podman build -t localhost/exam-ready-app:latest "$REPO_DIR/app"
ok "image built: localhost/exam-ready-app:latest"

# ── 9. Start app container ──────────────────────────────────────────────────
bold "==> 9/11  Starting exam-ready-app"
systemctl --user start exam-ready-app.service
for i in $(seq 1 30); do
  CODE=$(curl -sS -o /dev/null -w "%{http_code}" --max-time 2 "http://127.0.0.1:$APP_PORT/login" 2>/dev/null || echo 000)
  if echo "$CODE" | grep -qE '^(200|307)$'; then
    ok "app is responding on 127.0.0.1:$APP_PORT (took ${i}s, HTTP $CODE)"
    break
  fi
  sleep 1
  if [ "$i" = "30" ]; then
    err "app did not become ready in 30s"
    podman logs exam-ready-app 2>&1 | tail -30 || true
    exit 1
  fi
done

# ── 10. Migrate ─────────────────────────────────────────────────────────────
bold "==> 10/11  Running prisma migrate deploy"
podman exec exam-ready-app npx prisma migrate deploy
ok "migrations applied"

# ── 11. First-run seed (gated) ──────────────────────────────────────────────
bold "==> 11/11  Checking seed gate"
if [ "$(grep -E '^EXAMREADY_SEEDED=' "$ENV_FILE" 2>/dev/null | cut -d= -f2- || echo '')" != "1" ]; then
  podman exec exam-ready-app npx tsx prisma/seed.ts
  printf '\nEXAMREADY_SEEDED=1\n' >> "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  ok "seeded demo accounts (admin@bistecglobal.com / admin123!, candidate@bistecglobal.com / candidate123!)"
else
  warn "EXAMREADY_SEEDED=1 — skipping seed"
fi

bold ""
ok "Setup complete — https://$DOMAIN should be live once Cloudflare propagates"
